import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
       <div>this is sample deployment nextjs
        <h1>demo-deploy</h1>
        <img src='https://upcode.in/wp-content/uploads/2025/04/Upcode-logo-green-1536x360.webp' width={300}/>
        <img src='https://upcode.in/wp-content/uploads/2025/04/Upcode-logo-green-1536x360.webp' width={500}/>
        <h2>demo tooooo</h2>

       </div>
      </main>
    </>
  )
}
